interface Message {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

interface WorkItem {
  title: string;
  description?: string;
  squad?: { name: string } | null;
  impact_bucket_primary?: string | null;
  predicted_profitability_cr?: number | null;
  global_rank?: number | null;
  created_at: string;
}

export function generateSpecMarkdown(
  workItem: WorkItem,
  messages: Message[]
): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let markdown = `# Product Requirements Document: ${workItem.title}\n\n`;
  markdown += `**Created**: ${date}\n`;
  
  if (workItem.squad?.name) {
    markdown += `**Squad**: ${workItem.squad.name}\n`;
  }
  
  if (workItem.impact_bucket_primary) {
    markdown += `**Impact Bucket**: ${workItem.impact_bucket_primary}\n`;
  }
  
  if (workItem.predicted_profitability_cr) {
    markdown += `**Predicted Impact**: ₹${workItem.predicted_profitability_cr}Cr\n`;
  }
  
  if (workItem.global_rank) {
    markdown += `**Priority Rank**: #${workItem.global_rank}\n`;
  }
  
  markdown += `\n---\n\n`;

  // Add conversation
  markdown += `## Conversation History\n\n`;
  messages.forEach((msg) => {
    const role = msg.role === 'user' ? '**PM**' : '**AI Assistant**';
    markdown += `### ${role}\n\n`;
    markdown += `${msg.content}\n\n`;
  });

  markdown += `---\n\n`;
  markdown += `*Generated by Ascent Spec Writer on ${date}*\n`;

  return markdown;
}

export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
